const data = [
  {
    id: 11,
    adult: false,
    backdrop_path: '/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg',
    belongs_to_collection: {
      id: 10,
      name: 'Star Wars Collection',
      poster_path: '/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg',
      backdrop_path: '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg',
    },
    budget: 11000000,
    genres: [
      { id: 1, name: 'Adventure' },
      { id: 2, name: 'Science Fiction' },
      { id: 3, name: 'Action' },
    ],
    homepage: 'http://www.starwars.com/films/star-wars-episode-iv-a-new-hope',
    imdb_id: 'tt0076759',
    original_language: 'en',
    original_title: 'Star Wars',
    overview:
      'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire...',
    popularity: 91.676,
    poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
    production_companies: [
      { id: 1, name: '20th Century Fox' },
      { id: 2, name: 'Lucasfilm Ltd.' },
    ],
    production_countries: [
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    release_date: '1977-05-25',
    revenue: 775398007,
    runtime: 121,
    spoken_languages: [
      { iso_639_1: 'en', name: 'English' },
      { iso_639_1: 'es', name: 'Spanish' },
    ],
    status: 'Released',
    tagline: 'A long time ago in a galaxy far, far away...',
    title: 'Star Wars',
    video: false,
    vote_average: 8.204,
    vote_count: 19161,
  },
  {
    id: 12,
    adult: false,
    backdrop_path: '/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg',
    belongs_to_collection: {
      id: 11,
      name: 'Jurassic Park Collection',
      poster_path: '/bRAa4y0ayB2IvrCxRQ7bs2cKnxl.jpg',
      backdrop_path: '/6ELJEzQJ3Y45HczvreC3dg0GV5R.jpg',
    },
    budget: 63000000,
    genres: [
      { id: 1, name: 'Adventure' },
      { id: 2, name: 'Science Fiction' },
      { id: 3, name: 'Action' },
    ],
    homepage: 'http://www.jurassicpark.com/',
    imdb_id: 'tt0107290',
    original_language: 'en',
    original_title: 'Jurassic Park',
    overview:
      'A wealthy entrepreneur secretly creates a theme park featuring living dinosaurs drawn from prehistoric DNA...',
    popularity: 62.129,
    poster_path: '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
    production_companies: [{ id: 1, name: 'Universal Pictures' }],
    production_countries: [
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    release_date: '1993-06-11',
    revenue: 1079261473,
    runtime: 127,
    spoken_languages: [
      { iso_639_1: 'en', name: 'English' },
      { iso_639_1: 'es', name: 'Spanish' },
    ],
    status: 'Released',
    tagline: 'An adventure 65 million years in the making.',
    title: 'Jurassic Park',
    video: false,
    vote_average: 7.929,
    vote_count: 20776,
  },
  {
    id: 13,
    adult: false,
    backdrop_path: '/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg',
    belongs_to_collection: null,
    budget: 93000000,
    genres: [
      { id: 1, name: 'Adventure' },
      { id: 2, name: 'Fantasy' },
      { id: 3, name: 'Family' },
    ],
    homepage: 'http://www.harrypotter.com/',
    imdb_id: 'tt0241527',
    original_language: 'en',
    original_title: "Harry Potter and the Philosopher's Stone",
    overview:
      "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life...",
    popularity: 53.03,
    poster_path: '/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
    production_companies: [
      { id: 1, name: 'Warner Bros. Pictures' },
      { id: 2, name: 'Heyday Films' },
    ],
    production_countries: [
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    release_date: '2001-11-16',
    revenue: 974755371,
    runtime: 152,
    spoken_languages: [
      { iso_639_1: 'en', name: 'English' },
      { iso_639_1: 'fr', name: 'French' },
    ],
    status: 'Released',
    tagline: 'Let the magic begin.',
    title: "Harry Potter",
    video: false,
    vote_average: 7.976,
    vote_count: 22089,
  },
  {
    id: 14,
    adult: false,
    backdrop_path: '/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg',
    belongs_to_collection: null,
    budget: 75000000,
    genres: [
      { id: 1, name: 'Animation' },
      { id: 2, name: 'Adventure' },
      { id: 3, name: 'Comedy' },
    ],
    homepage: 'https://www.pixar.com/feature-films/toy-story',
    imdb_id: 'tt0114709',
    original_language: 'en',
    original_title: 'Toy Story',
    overview:
      "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene...",
    popularity: 83.038,
    poster_path: '/rhIRbceoE9lR4veEXuwCC2wARtG.jpg',
    production_companies: [
      { id: 3, name: 'Pixar Animation Studios' },
      { id: 12, name: 'Walt Disney Pictures' },
    ],
    production_countries: [
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    release_date: '1995-10-30',
    revenue: 373413297,
    runtime: 81,
    spoken_languages: [
      { iso_639_1: 'en', name: 'English' },
      { iso_639_1: 'es', name: 'Spanish' },
    ],
    status: 'Released',
    tagline: 'Hang on for the comedy that goes to infinity and beyond!',
    title: 'Toy Story',
    video: false,
    vote_average: 7.975,
    vote_count: 13621,
  },
  {
    id: 14,
    adult: false,
    backdrop_path: '/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg',
    belongs_to_collection: null,
    budget: 75000000,
    genres: [
      { id: 1, name: 'Animation' },
      { id: 2, name: 'Adventure' },
      { id: 3, name: 'Comedy' },
    ],
    homepage: 'https://www.pixar.com/feature-films/toy-story',
    imdb_id: 'tt0114709',
    original_language: 'en',
    original_title: 'Toy Story',
    overview:
      "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene...",
    popularity: 83.038,
    poster_path: '/rhIRbceoE9lR4veEXuwCC2wARtG.jpg',
    production_companies: [
      { id: 3, name: 'Pixar Animation Studios' },
      { id: 12, name: 'Walt Disney Pictures' },
    ],
    production_countries: [
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    release_date: '1995-10-30',
    revenue: 373413297,
    runtime: 81,
    spoken_languages: [
      { iso_639_1: 'en', name: 'English' },
      { iso_639_1: 'es', name: 'Spanish' },
    ],
    status: 'Released',
    tagline: 'Hang on for the comedy that goes to infinity and beyond!',
    title: 'Toy Story',
    video: false,
    vote_average: 7.975,
    vote_count: 13621,
  },
];

export default data;